### ISSUE TITLE
Crash on installing.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [xBlackCat/favoritefolders-idea-plugin#1]
```
What steps will reproduce the problem?
1. Installing plugin
2. Trying to configure
3.

What is the expected output? What do you see instead?
I excpected a picker, yet get a crash/spinner

What version of the product are you using? On what operating system?
Osx 10.7, php storm 5.0.4

Please provide any additional information below.

null
java.lang.NullPointerException
    at org.xblackcat.idea.favorites.AConfigPane$FavoriteFoldersConfigForm.reset(AConfigPane.java:121)
    at org.xblackcat.idea.favorites.AConfigPane.reset(AConfigPane.java:61)
    at com.intellij.openapi.options.newEditor.OptionsEditor.b(OptionsEditor.java:456)
    at com.intellij.openapi.options.newEditor.OptionsEditor.access$2500(OptionsEditor.java:67)
    at com.intellij.openapi.options.newEditor.OptionsEditor$8$1$1.run(OptionsEditor.java:424)
    at com.intellij.openapi.application.impl.ApplicationImpl.runEdtSafeAction(ApplicationImpl.java:1066)
    at com.intellij.openapi.options.newEditor.OptionsEditor$8$1.run(OptionsEditor.java:418)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:918)
    at com.intellij.openapi.options.newEditor.OptionsEditor$8.run(OptionsEditor.java:416)
    at com.intellij.openapi.application.impl.ApplicationImpl$6.run(ApplicationImpl.java:457)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:148)

```

Original issue reported on code.google.com by `71me...@gmail.com` on 26 Nov 2012 at 11:16

**Comment by xBlackCat** [comment]
Could you try to reproduce the issue with latest version of plugin (1.2.0.0)?
