### ISSUE TITLE
right click on folder, add to favourites broken in 129.17

### ISSUE THREAD

**Issue by GoogleCodeExporter** [xBlackCat/favoritefolders-idea-plugin#2]
```
129.17

open files | select folder | right click on folder, add to favourites

Error during dispatching of 
java.awt.event.MouseEvent[MOUSE_RELEASED,(301,427),absolute(924,573),button=1,mo
difiers=Button1,clickCount=1] on dialog2: parent must be showing: 
com.intellij.openapi.actionSystem.impl.ActionMenuItem[,1,169,209x19,invalid,alig
nmentX=0.0,alignmentY=0.0,border=com.intellij.ide.ui.laf.darcula.ui.DarculaMenuI
temBorder@1b68c3a,flags=392,maximumSize=,minimumSize=,preferredSize=,defaultIcon
=LazyIcon@ActionManagerImpl (path: /general/addFavoritesList.png, action class: 
class 
org.xblackcat.idea.favorites.AddFavoriteFolder),disabledIcon=com.intellij.openap
i.util.IconLoader$MyImageIcon@13ebc36,disabledSelectedIcon=,margin=javax.swing.p
laf.InsetsUIResource[top=2,left=2,bottom=2,right=2],paintBorder=false,paintFocus
=false,pressedIcon=,rolloverEnabled=false,rolloverIcon=,rolloverSelectedIcon=,se
lectedIcon=,text=Add to favorites]
java.lang.IllegalArgumentException: parent must be showing: 
com.intellij.openapi.actionSystem.impl.ActionMenuItem[,1,169,209x19,invalid,alig
nmentX=0.0,alignmentY=0.0,border=com.intellij.ide.ui.laf.darcula.ui.DarculaMenuI
temBorder@1b68c3a,flags=392,maximumSize=,minimumSize=,preferredSize=,defaultIcon
=LazyIcon@ActionManagerImpl (path: /general/addFavoritesList.png, action class: 
class 
org.xblackcat.idea.favorites.AddFavoriteFolder),disabledIcon=com.intellij.openap
i.util.IconLoader$MyImageIcon@13ebc36,disabledSelectedIcon=,margin=javax.swing.p
laf.InsetsUIResource[top=2,left=2,bottom=2,right=2],paintBorder=false,paintFocus
=false,pressedIcon=,rolloverEnabled=false,rolloverIcon=,rolloverSelectedIcon=,se
lectedIcon=,text=Add to favorites]
    at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.<init>(DialogWrapperPeerImpl.java:157)
    at com.intellij.openapi.ui.impl.DialogWrapperPeerFactoryImpl.createPeer(DialogWrapperPeerFactoryImpl.java:45)
    at com.intellij.openapi.ui.DialogWrapper.createPeer(DialogWrapper.java:692)
    at com.intellij.openapi.ui.DialogWrapper.<init>(DialogWrapper.java:234)
    at com.intellij.openapi.ui.DialogBuilder$MyDialogWrapper.<init>(DialogBuilder.java:313)
    at com.intellij.openapi.ui.DialogBuilder$MyDialogWrapper.<init>(DialogBuilder.java:306)
    at com.intellij.openapi.ui.DialogBuilder.<init>(DialogBuilder.java:66)
    at org.xblackcat.idea.favorites.Utils.selectFolder(Utils.java:130)
    at org.xblackcat.idea.favorites.AddFavoriteFolder.actionPerformed(AddFavoriteFolder.java:30)
    at com.intellij.openapi.fileChooser.actions.FileChooserAction.actionPerformed(FileChooserAction.java:37)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:151)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:256)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:892)
    at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:114)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:227)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:101)
    at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:512)
    at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
    at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:532)
    at java.awt.Component.processMouseEvent(Component.java:6505)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
    at java.awt.Component.processEvent(Component.java:6270)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4861)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
    at java.awt.Container.dispatchEventImpl(Container.java:2273)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:723)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:682)
    at java.awt.EventQueue$3.run(EventQueue.java:680)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:696)
    at java.awt.EventQueue$4.run(EventQueue.java:694)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:693)
    at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:686)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:507)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:334)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:244)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:163)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:155)
    at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:182)
    at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:221)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:219)
    at java.awt.Dialog.show(Dialog.java:1077)
    at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:698)
    at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:397)
    at com.intellij.openapi.ui.DialogWrapper.showAndGetOk(DialogWrapper.java:1458)
    at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1433)
    at com.intellij.openapi.fileChooser.ex.FileChooserDialogImpl.choose(FileChooserDialogImpl.java:130)
    at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:238)
    at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:217)
    at com.intellij.ide.actions.OpenFileAction.actionPerformed(OpenFileAction.java:89)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:151)
    at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:169)
    at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:132)
    at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:310)
    at java.awt.Component.processEvent(Component.java:6270)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4861)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
    at java.awt.Container.dispatchEventImpl(Container.java:2273)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:723)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:682)
    at java.awt.EventQueue$3.run(EventQueue.java:680)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:696)
    at java.awt.EventQueue$4.run(EventQueue.java:694)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:693)
    at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:686)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:507)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:334)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:244)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:163)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:151)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:147)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:139)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:97)

```

Original issue reported on code.google.com by `vojta.kr...@gmail.com` on 21 Mar 2013 at 11:18

**Comment by xBlackCat** [comment]
Fixed in v1.2.0.0
