### ISSUE TITLE
Exception on IntelliJ IDEA startup (2020.1 EAP)

### ISSUE THREAD

**Issue by Javaru** [xBlackCat/favoritefolders-idea-plugin#3]
The following exception occurs with v1.3 on startup of IntelliJ IDEA v2020.1 EAP build 201.6073.9. I know the v1.3 release note says "Prepare for Idea 2020.x" and therefore it may not be fully ready for 2020.1 yet. But I did want to give you a heads up on this exception. Thanks,

```
java.lang.Throwable: class org.xblackcat.idea.favorites.FavoriteFoldersPlugin it is service, use getService instead of getComponent
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getComponent(PlatformComponentManagerImpl.kt:328)
	at org.xblackcat.idea.favorites.AppInitializerListener.componentsInitialized(AppInitializerListener.java:18)
	at com.intellij.idea.ApplicationLoader$callAppInitialized$2$1.run(ApplicationLoader.kt:473)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:223)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:202)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:194)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by xBlackCat** [comment]
Did you still have the issue with version 1.3.1.1?
